// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4KMhVMW8x4bxzlJ5py771e1Vhx3uTLWo',
    appId: '1:615626382034:web:8954499359e9f866c82b0b',
    messagingSenderId: '615626382034',
    projectId: 'pizzahut-ca82a',
    authDomain: 'pizzahut-ca82a.firebaseapp.com',
    storageBucket: 'pizzahut-ca82a.appspot.com',
    measurementId: 'G-ELWFVK9FRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCShLyLRifd3gpV8DOrTQMRPtfCsIoWmv0',
    appId: '1:615626382034:android:51a0dde984c3b541c82b0b',
    messagingSenderId: '615626382034',
    projectId: 'pizzahut-ca82a',
    storageBucket: 'pizzahut-ca82a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNIaTJwwiQH-Fs--A6BucwD799O4dp54A',
    appId: '1:615626382034:ios:5136b5de8e9b08fac82b0b',
    messagingSenderId: '615626382034',
    projectId: 'pizzahut-ca82a',
    storageBucket: 'pizzahut-ca82a.appspot.com',
    iosBundleId: 'com.example.pizzahutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNIaTJwwiQH-Fs--A6BucwD799O4dp54A',
    appId: '1:615626382034:ios:d54431064233d499c82b0b',
    messagingSenderId: '615626382034',
    projectId: 'pizzahut-ca82a',
    storageBucket: 'pizzahut-ca82a.appspot.com',
    iosBundleId: 'com.example.pizzahutApp.RunnerTests',
  );
}
